### ISSUE TITLE
Draft spec for trait-association search

### ISSUE THREAD

**Issue by StevenCannon-USDA** [legumeinfo/website-ui-specs#6]
Please see draft spec for trait-association searches (for GWAS and QTL data), here:
https://github.com/legumeinfo/website-ui-specs/tree/main/trait-search

... and provide feedback. Please respond via this issue.
@sammyjava @That-Thing @maxglycine @jd-campbell @alancleary @adf-ncgr

**Comment by sammyjava** [comment]
Also a happy task for me if an intern doesn't take it on.

**Comment by StevenCannon-USDA** [comment]
@sammyjava Thanks - but I think Simon (@That-Thing) will do an excellent job on this. He's on it. We'll definitely ask for your review.

**Comment by jd-campbell** [comment]
@StevenCannon-USDA 
I agree that this is a good draft spec for a trait-associated search.  I particularly like the 'Study ID" as a good way to search for data.  I am just wondering if "Study ID" is the right term to use, since the DOI or PMID is usually associated with a research paper.  The e.g. under the text box does give the user an idea what to enter.  
I am just thinking of ways the user can mess this up.

**Comment by StevenCannon-USDA** [comment]
@jd-campbell I'm open. What term or description do you propose?

**Comment by jd-campbell** [comment]
@StevenCannon-USDA  
Here are my suggestions:

- Publication ID
- Manuscript ID 

I am also open if you can think of a different word.

**Comment by StevenCannon-USDA** [comment]
@jd-campbell "Publication ID" looks good to me. I'll make that change.

**Comment by StevenCannon-USDA** [comment]
I have updated the spec to change "Study ID" ==> "Publication ID" and to add discussion of report layouts (vertical or tabular). I consider the spec "implementation-ready" at this point.
